"""add llm enrichment columns and llm_cache

Revision ID: 0b5213412276
Revises: f7a2b4c83e91
Create Date: 2026-05-21 16:14:38.354548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b5213412276'
down_revision: Union[str, Sequence[str], None] = 'f7a2b4c83e91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_cache',
    sa.Column('cache_key', sa.Text(), nullable=False),
    sa.Column('hh_resume_id', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default='NOW()', nullable=False),
    sa.ForeignKeyConstraint(['hh_resume_id'], ['resumes.hh_resume_id'], ),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_index('idx_llm_cache_resume', 'llm_cache', ['hh_resume_id'], unique=False)
    # server_default='FALSE' required so existing rows get a value before NOT NULL is enforced
    op.add_column('events', sa.Column('llm_enriched', sa.Boolean(), server_default='FALSE', nullable=False))
    op.drop_index(op.f('idx_events_pending_notion'), table_name='events', postgresql_where='(notion_synced = false)')
    op.create_index('idx_events_pending_llm', 'events', ['llm_enriched'], unique=False, postgresql_where='llm_enriched = FALSE')
    op.drop_column('events', 'notion_synced')
    op.add_column('resumes', sa.Column('fit_score', sa.Integer(), nullable=True))
    op.add_column('resumes', sa.Column('llm_score', sa.Integer(), nullable=True))
    op.add_column('resumes', sa.Column('llm_verdict', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('llm_comment', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('llm_red_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('resumes', sa.Column('llm_real_role', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('llm_scored_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('resumes', sa.Column('llm_content_hash', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('score_total', sa.Integer(), nullable=True))
    op.add_column('resumes', sa.Column('screening_status', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('screened_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('resumes', sa.Column('screened_by', sa.Text(), nullable=True))
    op.drop_column('resumes', 'notion_page_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('notion_page_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('resumes', 'screened_by')
    op.drop_column('resumes', 'screened_at')
    op.drop_column('resumes', 'screening_status')
    op.drop_column('resumes', 'score_total')
    op.drop_column('resumes', 'llm_content_hash')
    op.drop_column('resumes', 'llm_scored_at')
    op.drop_column('resumes', 'llm_real_role')
    op.drop_column('resumes', 'llm_red_flags')
    op.drop_column('resumes', 'llm_comment')
    op.drop_column('resumes', 'llm_verdict')
    op.drop_column('resumes', 'llm_score')
    op.drop_column('resumes', 'fit_score')
    op.add_column('events', sa.Column('notion_synced', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index('idx_events_pending_llm', table_name='events', postgresql_where='llm_enriched = FALSE')
    op.create_index(op.f('idx_events_pending_notion'), 'events', ['notion_synced'], unique=False, postgresql_where='(notion_synced = false)')
    op.drop_column('events', 'llm_enriched')
    op.drop_index('idx_llm_cache_resume', table_name='llm_cache')
    op.drop_table('llm_cache')
    # ### end Alembic commands ###
