"""initial schema

Revision ID: 3dafa61f6780
Revises:
Create Date: 2026-05-20 15:05:12.762293

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3dafa61f6780"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parser_runs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "started_at", sa.TIMESTAMP(timezone=True), server_default="NOW()", nullable=False
        ),
        sa.Column("finished_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("searches_run", sa.Integer(), nullable=False),
        sa.Column("resumes_seen", sa.Integer(), nullable=False),
        sa.Column("resumes_viewed", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "resumes",
        sa.Column("hh_resume_id", sa.Text(), nullable=False),
        sa.Column(
            "first_seen_at", sa.TIMESTAMP(timezone=True), server_default="NOW()", nullable=False
        ),
        sa.Column(
            "last_seen_at", sa.TIMESTAMP(timezone=True), server_default="NOW()", nullable=False
        ),
        sa.Column("notion_page_id", sa.Text(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("hh_resume_id"),
    )
    op.create_index("idx_resumes_last_seen", "resumes", ["last_seen_at"], unique=False)
    op.create_table(
        "searches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("position_code", sa.Text(), nullable=False),
        sa.Column("position_name", sa.Text(), nullable=False),
        sa.Column("hh_params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("portrait", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), server_default="NOW()", nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("position_code"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("hh_resume_id", sa.Text(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("search_id", sa.Integer(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("fit_score", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), server_default="NOW()", nullable=False
        ),
        sa.Column("notion_synced", sa.Boolean(), nullable=False),
        sa.Column("telegram_sent", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hh_resume_id"],
            ["resumes.hh_resume_id"],
        ),
        sa.ForeignKeyConstraint(
            ["search_id"],
            ["searches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_events_pending_notion",
        "events",
        ["notion_synced"],
        unique=False,
        postgresql_where="notion_synced = FALSE",
    )
    op.create_index(
        "idx_events_pending_telegram",
        "events",
        ["telegram_sent"],
        unique=False,
        postgresql_where="telegram_sent = FALSE",
    )
    op.create_table(
        "snapshots",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("hh_resume_id", sa.Text(), nullable=False),
        sa.Column(
            "fetched_at", sa.TIMESTAMP(timezone=True), server_default="NOW()", nullable=False
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hh_resume_id"],
            ["resumes.hh_resume_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hh_resume_id", "content_hash", name="uq_snapshots_dedup"),
    )
    op.create_index(
        "idx_snapshots_resume_time", "snapshots", ["hh_resume_id", "fetched_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_snapshots_resume_time", table_name="snapshots")
    op.drop_table("snapshots")
    op.drop_index(
        "idx_events_pending_telegram", table_name="events", postgresql_where="telegram_sent = FALSE"
    )
    op.drop_index(
        "idx_events_pending_notion", table_name="events", postgresql_where="notion_synced = FALSE"
    )
    op.drop_table("events")
    op.drop_table("searches")
    op.drop_index("idx_resumes_last_seen", table_name="resumes")
    op.drop_table("resumes")
    op.drop_table("parser_runs")
    # ### end Alembic commands ###
