"""add oauth_tokens and dictionaries_cache

Revision ID: 6459be1c4035
Revises: 3dafa61f6780
Create Date: 2026-05-20 15:23:51.616965

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6459be1c4035"
down_revision: str | Sequence[str] | None = "3dafa61f6780"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dictionaries_cache",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "fetched_at", sa.TIMESTAMP(timezone=True), server_default="NOW()", nullable=False
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "oauth_tokens",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=False),
        sa.Column("token_type", sa.Text(), server_default="bearer", nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("scope", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), server_default="NOW()", nullable=False
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), server_default="NOW()", nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("oauth_tokens")
    op.drop_table("dictionaries_cache")
    # ### end Alembic commands ###
