"""add notifications_sent and app_config

Revision ID: 9808af65796c
Revises: e2f3a4b5c6d7
Create Date: 2026-05-25 16:35:45.236225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9808af65796c'
down_revision: Union[str, Sequence[str], None] = 'e2f3a4b5c6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default='NOW()', nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('notifications_sent',
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_message_id', sa.BigInteger(), nullable=False),
    sa.Column('sent_at', sa.TIMESTAMP(timezone=True), server_default='NOW()', nullable=False),
    sa.Column('screening_status', sa.Text(), nullable=True),
    sa.Column('screened_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('screened_by', sa.BigInteger(), nullable=True),
    sa.Column('screened_by_username', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications_sent')
    op.drop_table('app_config')
    # ### end Alembic commands ###
